/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sqgqsdexujosloavpuso"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZ3FzZGV4dWpvc2xvYXZwdXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5ODc1NjMsImV4cCI6MjA4NjU2MzU2M30.l1BS-QUs0rNJmua9FE-Iz5iXm1MaFNyLbE6EcObmxEg"